A = int(input("Digite o valor de A: "))
B = int(input("Digite o valor de B: "))
C = int(input("Digite o valor de C: "))
D = int(input("DIGITE O VALOR DE D: "))


if(A%2==0 and A%3==0):
    print(F'O VALOR {A} É DIVISÍVEL POR 2 E 3')
if(B%2==0 and B%3==0):
    print(F'O VALOR {B} É DIVISÍVEL POR 2 E 3')
if(C%2==0 and C%3==0):
    print(F'O VALOR {C} É DIVISÍVEL POR 2 E 3')
if(D%2==0 and D%3==0):
    print(F'O VALOR {D} É DIVISÍVEL POR 2 E 3')